### ISSUE TITLE
你好，问下，解析地址时 项目中 缺少  文件额

### ISSUE THREAD

**Issue by xtsteven** [liyuan3210/adr#1]
你好，问下，解析地址时 项目中 缺少 /home/liyuan/soft/adr/region_2.txt 这个路径的 region_2.txt 这个文件，可以的话，能发上来么，谢谢

**Comment by liyuan3210** [comment]
你好,缺少的文件在百度分享https://pan.baidu.com/s/1SGynRTQxl_toMjrbomcXAw里面
